title: Lukas Rosenberger
#position: Ph.D. Candidate
affiliation: Munich Graduate School of Economics
#email: lukas.rosenberger@econ.lmu.de
keywords: Lukas Rosenberger LMU Munich economics economic history job market candidate
#google_scholar: https://scholar.google.com/
#github_link: https://github.com/yaoyao-liu/minimal-light
avatar: ./assets/img/Lukas_2019_SW.png
#google_analytics: UA-111540567-4
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png
description: Lukas Rosenberger LMU Munich economics economic history job market candidate
#canonical: 
remote_theme: yaoyao-liu/minimal-light
